package com.project.formulario.formulariocovid.enun;

public enum Funcao {
	
	ROLE_GERENTE,
	ROLE_SUPERVISOR,
	ROLE_ADMINISTRATIVO,
	ROLE_TECNICO_INFORMATICA,
	ROLE_AUXILIAR_INFORMATICA,
	ROLE_ASSISTENTE_ADMINISTRATIVO,
	ROLE_AXILIAR_LIMPEZA,
}
